#!/bin/bash

if [ -z $( type -p grep ) ]
then
  PATH="${PATH}:/bin"
fi

for dir in ~/dev*/* /C/Dev*/* /c/dev*/*
do
	if [ -d ${dir}/.git ] 
	then
		echo $dir 
		pushd $dir > /dev/null 
    for b in $( git for-each-ref --format='%(refname:short)' \
      --sort=-committerdate refs/heads/ )
    do
      git branch -vv -l "${b}" | grep -q ": gone" && git branch -D "${b}"
    done
    git gc
		popd > /dev/null 
	fi 
done

