#!/bin/sh

params=( ${@} )

# Split full branch names (eg. "<remote>/<branch>") into parts
[ ${#params[@]} = 1 ] && \
  params=( $( echo "${params[@]}" | sed "s/\//\n/" ) )

# Set up or update the branch
[ ${#params[@]} = 2 ] && \
  git fetch ${params[0]} && \
    ( git checkout -b ${params[0]}--${params[1]} \
      -t ${params[0]}/${params[1]} || \
      git checkout ${params[0]}--${params[1]} ) && \
      git pull && \
        exit 0 || \
echo "usage: git review <remote> <branch>" >&2 && \
  exit 1
