#!/bin/bash

branch=$( git rev-parse --abbrev-ref --symbolic-full-name "@" )
remote=$( git rev-parse --abbrev-ref --symbolic-full-name "@{u}" \
              2>/dev/null )
push=$( git rev-parse --abbrev-ref --symbolic-full-name "@{push}" \
              2>/dev/null )

[[ "${remote}" != "" ]] && git fetch || echo New branch

unset ci
if [[ "${1}" == "-ci" || "${1}" == "ci" ]]
then
  shift
  ci=1
fi

defaultRemote=$( git config checkout.defaultRemote )
if [[ -z "${defaultRemote}" ]]
then
  defaultRemote=origin
fi

git diff --quiet --staged &&
  ( git verify-commit HEAD || git commit --amend --no-edit -S ) &&
    ( git push --force-with-lease "${@}" ||
      git push "${@}" ||
      ( [[ "${remote}" != "" && "${push}" == "" ]] &&
      echo "Not pushing: ${branch:-???} from ${remote:-???} to ${push:-???}" ) ||
      git push "${@}" --set-upstream "${defaultRemote}" "${branch}" ) &&
    ( [[ -z "${ci}" ]] && exit 0 ||
      git push --force-with-lease ci
        "${branch}":"ed-${branch}" )
# https://developer.atlassian.com/blog/2015/04/force-with-lease/

