#!/bin/bash

# Usage: git allpull directory [...]

for dir in "${@}"
do
  echo $dir
  pushd $dir || continue
  git pull ||
  (
    branch=$( git rev-parse --abbrev-ref --symbolic-full-name "@" ) &&
      repo=$( git config "branch.${branch}.remote" ) &&
      git pull "${repo}"
  )
  popd
done
