#!/bin/sh

# upstream=${2:-upstream/develop}
set -e
remote=${1:-upstream}
refspec=${2:-develop}
shift 2
for b in "${@}"
do
  echo -e "\n\n${b}\n\n"
  git checkout "${b}" && \
    git pull && \
      # git rebase "${upstream}"
      git pull "${remote}" "${refspec}" && \
      	echo -e "\nPushing ${b}" && \
        	git signpush || \
          		exit 1
done
