#!/bin/bash

search=( ~/dev*/* /C/Dev*/* /c/dev*/* )
if [[ $# -gt 0 ]]
then
  search=( "${@}" )
fi

for dir in "${search[@]}"
do
  if [ -d ${dir}/.git ]
  then
    echo $dir
    pushd $dir > /dev/null
    git fetch --all -p --jobs=$(nproc) &
    popd > /dev/null
  fi
done
jobs
wait
