#!/bin/bash

if [[ "$( git config commit.gpgsign )" == "true" ]]
then
  keys=( $( git config --get-all user.signingkey ) )
  for k in "${keys[@]}"
  do
    echo "Checking that passphrase for ${k} can be accessed."
    echo | gpg --pinentry-mode loopback -o /dev/null --sign --armor \
      --local-user "${k}" -
    code=$?
    if [[ "$code" -ne 0 ]]
    then
      echo "Unable to sign using key ${k}."
      echo "Fix that before writing a commit message that will get lost."
      echo "e.g. echo | gpg --sign --armor --local-user ${k}"
      exit $code
    fi
  done
fi
