#!/bin/bash

~/.git/hooks/post-checkout "${@}"

# Only do these validations on a branch checkout, which includes `git
# checkout` with no parameters. https://git-scm.com/docs/githooks
if [[ $3 -eq 1 ]]
then
  # Reformat on checkout, if the current branch has instructions
  if [[ -f .clang-format ]]
  then
    compare=$( [ "$1" = "$2" ] && echo "upstream/develop" || echo "$1" )
    echo -e "\nFormatting files changed since $compare"
    # Uncomment the following line in Windows, and confirm the correct path
    # to your LLVM install. But note that there are incompatibilities with
    # the Windows version so you may not want to use this hook in Windows.
    PATH="/c/Program Files/LLVM/bin/:${PATH}"
    # find src/ripple src/test -type f \! -name 'AccountTxPaging.cpp' \( \
    #   -name '*.cpp' -o -name '*.h' -o -name '*.ipp' \) -print0 \
    #   | xargs -0 clang-format -i
    git-clang-format --extensions c,cpp,h,cxx,ipp $compare
  else
    echo -e "\nNot formatting code on older branch"
  fi
fi
