#!/bin/bash

# Format the files changed since the last commit, both staged and unstaged.
git-clang-format --extensions c,cpp,h,cxx,ipp

# Only uncomment the following line if you want to aggressively ensure
# that all formatting across the project is correct, and your version
# of `clang-format` doesn't have any incompatibilities.
# find src/ripple src/test -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.ipp' \) -print0 | xargs -0 clang-format -i

# Comment the following line if you want to let the commit complete even if
# there are formatting problems.
git diff --exit-code
