#!/bin/bash

~/.git/hooks/post-checkout "${@}"

# Reformat on checkout, if the current branch has been formatted already
if git merge-base --is-ancestor 50760c693510894ca368e90369b0cc2dabfd07f3 HEAD
then
  echo -e "\nCalling clang-format on all source files"
  # Uncomment the following line in Windows, and confirm the correct path
  # to your LLVM install. But note that there are incompatibilities with
  # the Windows version so you may not want to use this hook in Windows.
  PATH="/c/Program Files/LLVM/bin/:${PATH}"
  # find src/ripple src/test -type f \! -name 'AccountTxPaging.cpp' \( \
  #   -name '*.cpp' -o -name '*.h' -o -name '*.ipp' \) -print0 \
  #   | xargs -0 clang-format -i
  git-clang-format --extensions c,cpp,h,cxx,ipp $2
else
  echo -e "\nNot formatting code on older branch"
fi

