#!/bin/bash

# Run this after a fresh clone to do quick setup

hookspath=$( git config --global core.hookspath )
if [ -z "${hookspath}" ]
then
  hookspath=${HOME}/.git/hooks/
  git config --global core.hookspath "${hookspath}"
fi
if [ ! -d "${hookspath}" ]
then
  mkdir -pv "${hookspath}"
fi

for file in *
do
  if [[ "${file}" == "install" || "${file}" =~ "~" || \
    "${file}" =~ "rippled" || ! "${file}" =~ "git" ]]
  then
    # echo -e "Skipping ${file}\n"
    continue
  fi

  if [[ "${file}" =~ "githooks-" ]]
  then
    dest="${hookspath}/$( echo ${file} | sed 's/^githooks-//' )"
  else
    dest="${HOME}/bin/${file}"
  fi

  if [[ -e "${dest}" ]]
  then
    if ! cmp "${file}" "${dest}"
    then
      echo -e "\"${file}\" already found at ${dest}. Will not overwrite."
      # ls -l "${file}" "${dest}"
      echo -e "\n\n"
    fi
    continue
  fi

  ln -sv "$(pwd)/${file}" "${dest}"
  echo
done
